### ISSUE TITLE
Can I use your package with 2-factor auth?

### ISSUE THREAD

**Issue by krzysztofzuraw** [blacs30/bitwarden-alfred-workflow#1]
Hello,
I tried to use your workflow with my bitwarden but I have the following error:
![zrzut ekranu 2018-08-02 o 13 53 30](https://user-images.githubusercontent.com/9116238/43582260-2715bc84-965c-11e8-9ef9-a1ebdfe4af78.png)

**Comment by blacs30** [comment]
Hi @krzysztofzuraw ,

thank you for creating this issue.
Currently it is not working with 2fa as I didn't use it in my self hosted environment yet.
However I will look into this soon unless you want to.

**Comment by blacs30** [comment]
Hi @krzysztofzuraw,

I have uploaded version [1.1.0](https://github.com/blacs30/bitwarden-alfred-workflow/releases/tag/1.1.0) which adds the option for 2FA.


As I only have an Authenticator App I wasn't able to test it with other options that Bitwarden supports.
Please let me know if this solved the issue for you.
