### ISSUE TITLE
Error: Library not loaded

### ISSUE THREAD

**Issue by mmahmad** [blacs30/bitwarden-alfred-workflow#104]
Hi,

Today, I was automatically logged out of Bitwarden. When I tried to log back in, I got an error while it was trying to load some library (screenshot attached).

I deleted the entire workflow, and downloaded the latest one, but the error continues to occur when I try to log in.

![image](https://user-images.githubusercontent.com/4930049/130301744-9164a608-971b-46df-9fa5-2519834ccb51.png)

**Comment by luckman212** [comment]
@mmahmad that's a weird one. What's the output of these Terminal commands on your system?

```
ls -l /usr/local/opt/icu4c/lib

bw -v

brew info icu4c

brew doctor
```

**Comment by mmahmad** [comment]
Looks like there was a problem with Homebrew and python 3.8/3.9 installation. 

Got fixed when I followed [this](https://stackoverflow.com/questions/64362772/switching-python-version-installed-by-homebrew)
