### ISSUE TITLE
Add auto update

### ISSUE THREAD

**Issue by mrvkino** [blacs30/bitwarden-alfred-workflow#108]
Hi,

it would be nice to have automatic update with the workflow.

There are two way to easily add it, one is with this [framework](https://github.com/deanishe/alfred-workflow) or more pertinent for this project this pre-made [workflow](https://github.com/vitorgalvao/alfred-workflows/tree/master/OneUpdater) to add to an existing workflow.

**Comment by blacs30** [comment]
Thanks for this feature request @mrvkino.
Auto update is already part of this workflow - doesn't it work for you?
@luckman212  does auto update work for you?

**Comment by luckman212** [comment]
@blacs30 Yes it seems to work for me, although I always update manually 😛

![image](https://user-images.githubusercontent.com/1992842/133667153-2c43b5a9-c0bf-4d6b-adb3-653b7a902fe9.png)

![image](https://user-images.githubusercontent.com/1992842/133667189-9f33f960-7d65-414a-9c3b-9a3809939b47.png)

![image](https://user-images.githubusercontent.com/1992842/133667128-b85c660b-47e3-4f3b-8850-463ece5ce28d.png)

**Comment by mrvkino** [comment]
Ha! I need to take a bit more time to RTFM. Well that was easy.

Thanks for the swift response.
