### ISSUE TITLE
Fussy search

### ISSUE THREAD

**Issue by mrvkino** [blacs30/bitwarden-alfred-workflow#109]
Hi,

I have in my bitwarden vault password for `accounts.spotify.com`. But if I search in Alfred with `.bw spotify` it does not show. I have to type `.bw accounts.spo` to see it.

It would be nice to have some fuzzy search like Alfred to find the password.

**Comment by blacs30** [comment]
@mrvkino  you can switch between 2 filtering modes https://github.com/blacs30/bitwarden-alfred-workflow#search---filtermode

see also this comment https://github.com/blacs30/bitwarden-alfred-workflow/issues/107#issuecomment-920118909

**Comment by mrvkino** [comment]
Ok! seems to be working better. typing `spotify` return a bunch of result without the word Spotify in it. The password for Spotify ranks low, but it is findable now.
