### ISSUE TITLE
.bw url not executing

### ISSUE THREAD

**Issue by dpanummer3** [blacs30/bitwarden-alfred-workflow#113]
Hi everything seems to be working fine. Downloaded bw cli, node etc. But when I type in .bw and place the name of the account of a website. My library is indeed searchable. It just doesn't execute. It doesn't load the website and fills in the account and username. The Alfred bar just disappears. I have MacOs Big Sur 11.5.2, Alfred 4.5.1, Bitwarden CLI, NPM 7.21.1 and Node v16.9.1. Also granted Bitwarden app in accessibility. Also logged in and unlocked via .bitauth

Debugging mode shows the following:

19:42:05.836] STDERR: Bitwarden v2[Run Script] 🍺
19:42:05 workflow.go:328: -------- Bitwarden v2/2.4.0 (AwGo/0.27.1) --------
19:42:05 main.go:143: &main.options{Search:false, Config:false, SetConfigs:false, Auth:false, Sfa:false, Lock:false, Icons:false, Folder:false, Unlock:false, Login:false, Logout:false, Sync:false, Open:false, GetItem:true, Force:false, Totp:false, Last:false, Background:false, Id:"7d3d57d2-f4fb-49f8-9dbb-ad7b00f65855", Query:"login.password", Attachment:"", Output:""}
19:42:05 main.go:145: args=[]string{"-getitem", "-id", "7d3d57d2-f4fb-49f8-9dbb-ad7b00f65855", "login.password"} => []string{"login.password"}
19:42:05 main.go:146: (main.config) {
 AutoFetchIconCacheAge: (int) 1440,
 AutoFetchIconMaxCacheAge: (time.Duration) 24h0m0s,
 BwconfKeyword: (string) (len=10) ".bitconfig",
 BwauthKeyword: (string) (len=8) ".bitauth",
 BwKeyword: (string) (len=3) ".bw",
 BwfKeyword: (string) (len=5) ".bitf",
 BwExec: (string) (len=2) "bw",
 BwDataPath: (string) "",
 Debug: (bool) false,
 Email: (string) (len=22) "private@gmail.com",
 EmptyDetailResults: (bool) false,
 IconCacheAge: (int) 43200,
 IconCacheEnabled: (bool) true,
 IconMaxCacheAge: (time.Duration) 720h0m0s,
 MaxResults: (int) 1000,
 Mod1: (string) (len=3) "alt",
 Mod1Action: (string) (len=13) "username,code",
 Mod2: (string) (len=5) "shift",
 Mod2Action: (string) (len=3) "url",
 Mod3: (string) (len=4) "ctrl",
 Mod3Action: (string) (len=4) "totp",
 Mod4: (string) (len=7) "cmd,opt",
 Mod4Action: (string) (len=4) "more",
 NoModAction: (string) (len=13) "password,card",
 OutputFolder: (string) (len=29) "/Users/private/Downloads/",
 Path: (string) (len=101) "/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/bin:/usr/sbin:/usr/local/bin/bw",
 ReorderingDisabled: (bool) true,
 Server: (string) (len=21) "https://bitwarden.com",
 Sfa: (bool) false,
 SfaMode: (int) 0,
 SyncCacheAge: (int) 10080,
 SyncMaxCacheAge: (time.Duration) 168h0m0s,
 TitleWithUser: (bool) true,
 TitleWithUrls: (bool) true
}
19:42:05 bitwarden.go:235: Getting item for id 7d3d57d2-f4fb-49f8-9dbb-ad7b00f65855
19:42:05 workflow.go:405: ------------------ 49.519114ms -------------------
[19:42:05.863] Bitwarden v2[Run Script] Processing complete
[19:42:05.864] Bitwarden v2[Run Script] Passing output 'Private' to Copy to Clipboard
[19:42:05.867] Bitwarden v2[Run Script] Passing output 'Private' to Arg and Vars
[19:42:05.868] Bitwarden v2[Arg and Vars] Processing complete
[19:42:05.869] Bitwarden v2[Arg and Vars] Passing output 'Copy Password for user:
private@gmail.com' to Post Notification

Can you anything suspicious? Or do you have advice how to fix this problem?

If you can be of any help it would be greatly appreciated!

Kind regards,

David

**Comment by blacs30** [comment]
Hi David,

thanks for opening this issue and posting already the logs. 
From what I see is that you copied the password for the user `private@gmail.com` - if you want to open the URL you need to press one of the modifier keys. The default is SHIFT and all the different modifier keys available for an item are shown under an entry in the workflow.
However this workflow doesn't autofill user and password when a URL is opened, that would be part of the browser extension.
You can also change the modifier key / action  assignment. https://github.com/blacs30/bitwarden-alfred-workflow#modifier-actions-explained

**Comment by dpanummer3** [comment]
Thanks for your quick response. Didn't know I had to press shift, even though it's clearly marked @_@. Thanks! 

Second question: 

Is there a way to autofill user and password, when your extension in your browser is enabled and unlocked (I also have the Bitwarden app installed)? In other words, could I change something in the configuration to make it possible? I really loved that feature from the 1password workflow. 

Sorry for all the n00b questions :)

Kind regards,

David

**Comment by blacs30** [comment]
No problem.
The autofill option is in the Bitwarden browser extension in 
settings  > options (further at the end) > autofill

[Personally I don't use it though]

Could you link me the 1password Alfred workflow, sounds interesting that they've implemented an autofill feature directly from the workflow. Something I could consider to add to the Bitwarden workflow I think.

**Comment by dpanummer3** [comment]
Thanks! I was obviously looking in the wrong direction hehe. 

1password is a preinstalled feature of Alfred's powerpack. Unfortunately I can't see that there's an option to check or edit their workflow. 

I do now that it is bookmark based, and I believe that in the 1password extension, autofill is set on default. So that could be the answer.

https://www.alfredapp.com/help/features/1password/

See screenshot:

<img width="649" alt="Alfred Preferences 2021-09-20 13-55-06" src="https://user-images.githubusercontent.com/26124855/133998070-ab1c68df-23bd-4f8b-9b04-b56d0fc800ca.png">

But many thanks, it's now working just the way I like it!

Kind regards,

David
