### ISSUE TITLE
Error: error: unknown option '--passwordenv'

### ISSUE THREAD

**Issue by Stooovie** [blacs30/bitwarden-alfred-workflow#115]
I'm getting `Error: error: unknown option '--passwordenv'` notification upon entering login. 

Bitwarden 1.28.3, workflow 2.4.0, Big Sur 11.6. 

Alfred is added to Security/Developer tools, path to /usr/local/bin/bw is added into PATH. 

Please help.

**Comment by blacs30** [comment]
I'm sorry, somehow I have overlooked the email to this issue.
May I ask how you install bitwarden cli?
I don't see a version 1.28.3, the latest is 1.19.1 and that contains the `--passwordenv` parameter
https://github.com/bitwarden/cli/releases/tag/v1.19.1
