### ISSUE TITLE
Open in "Bitwarden" action

### ISSUE THREAD

**Issue by durandom** [blacs30/bitwarden-alfred-workflow#126]
Can we have a "open item in bitwarden" action?
Like the 1p action.

Or are we missing APIs or ABIs here?

<img width="735" alt="image" src="https://user-images.githubusercontent.com/161888/158657328-9291f1e7-1adf-4285-88e4-14e8b187b1b9.png">

**Comment by blacs30** [comment]
Hi @durandom, 
what should this action "open item in bitwarden" do? I've never used 1password. 
Should it open the selected item in the Bitwarden macOS application?

**Comment by durandom** [comment]
@blacs30 exactly. It opens the native mac app with the item selected. 
It useful if you want to edit the entry or just need to copy past more fields than one

**Comment by durandom** [comment]
<img width="409" alt="image" src="https://user-images.githubusercontent.com/161888/158954592-4411e182-bb82-4e9a-949c-874b307919dc.png">

actually the screenshot was wrong. this is how it looks like

**Comment by blacs30** [comment]
Sorry for the late reply @durandom 
This would be possible by linking to the Bitwarden web vault I believe:
https://bitwarden.com/help/link-to-an-item/

Would that be acceptable? I'm not sure if that would be possible with the macOS app of Bitwarden as well.

**Comment by durandom** [comment]
sure, whatever works :) and thanks for developing this workflow

**Comment by blacs30** [comment]
Version 2.4.5 is out and has this feature. It's okay-ish to edit an item this way (open in quickly in the web ui) but for each item  I need to login again. Little bit annoying if it was some very frequent activity.

**Comment by durandom** [comment]
@blacs30 thanks for your awesome work. It's better than nothing, let's hope the desktop app will get the same linking feature
