### ISSUE TITLE
cannot login - Passing output 'Error:    error: unknown option `--passwordenv

### ISSUE THREAD

**Issue by Stooovie** [blacs30/bitwarden-alfred-workflow#128]
After logging and entering 2FA, I'm getting  `Passing output 'Error: 
  error: unknown option `--passwordenv'`

 in the debug console. Alfred 4.6.5, Monterey 12.3.1.  BW 1.32.1. 
I tried logging in via API as well but as that requires password too, I'm stuck on the same error. Paths have been modified, bw cli is installed. Any tips? Thanks.

EDIT: for some reason installing bw cli via Homebrew didn't work properly. Downloading the binary and manually placing it into /usr/local/bin did the trick. It works now.

**Comment by blacs30** [comment]
Great to hear. 
I was wondering about the bitwarden cli version, because officially there is no 1.32.1 yet. https://github.com/bitwarden/cli

**Comment by Stooovie** [comment]
That's just my mistake. That's the Bitwarden version. bw cli is 1.19.1. God knows why it didn't work via Homebrew, there were no error messages during installation.

**Comment by Stooovie** [comment]
On my second Mac, I did the same thing, but am unable to get over the "Cache expired/not existing" message no matter what I do. Any tips? Thanks.

**Comment by blacs30** [comment]
just noticed now your edit. good to hear it works now.
A future plan, if I have more time, is to move to api only and remove the dependency to the Bitwarden CLI. That should help a lot.  It's much work though.
