### ISSUE TITLE
V. 1.37 workflow package update breaks support  for Alfred 3

### ISSUE THREAD

**Issue by rustycamper** [blacs30/bitwarden-alfred-workflow#13]
Latest workflow package update breaks the workflow for Alfred version 3 (and probably earlier). Alfred complains of an incompatible workflow version and prompts user to upgrade to Alfred v. 4.

**Comment by blacs30** [comment]
Thank you @rustycamper for pointing this out. 
I've released version [1.2.5](https://github.com/blacs30/bitwarden-alfred-workflow/releases/tag/1.2.5) with the note that it's the last version with support for Alfred 3
