### ISSUE TITLE
Faced the same issue with the latest version of the workflow (2.4.3).

### ISSUE THREAD

**Issue by blacs30** [blacs30/bitwarden-alfred-workflow#130]
Faced the same issue with the latest version of the workflow (2.4.3).
Steps:
1. Tried to use api_key as auth method. Did not work (but did not debug the reason)
2. Tried the password method, failed and started debugging. Firstly, had to delete the record from the keychain, cause wf was complaining about existing key. But it did not solve the issue. Only logging in through CLI itself helped.

_Originally posted by @Emptyfruit in https://github.com/blacs30/bitwarden-alfred-workflow/issues/120#issuecomment-1141815036_

**Comment by blacs30** [comment]
@Emptyfruit thanks for reporting this issue.
Which bitwarden cli version do you have installed?

**Comment by Emptyfruit** [comment]
@blacs30 1.22.1

**Comment by blacs30** [comment]
Does it work now for you @Emptyfruit with the latest workflow version?

**Comment by blacs30** [comment]
Please reopen if still present
