### ISSUE TITLE
Keep Appear Login

### ISSUE THREAD

**Issue by victorchor2868** [blacs30/bitwarden-alfred-workflow#131]
After filling in the password and verification code, it's keep logged out and can't log in, can you teach me which step was i wrong?
<img width="713" alt="CleanShot 2022-06-10 at 11 49 54@2x" src="https://user-images.githubusercontent.com/87065622/172987017-3d5543a4-7d4c-4d2f-97e6-a1ccd6187484.png">
.

**Comment by victorchor2868** [comment]
![Uploading CleanShot 2022-06-10 at 11.59.18@
<img width="465" alt="CleanShot 2022-06-10 at 11 59 29@2x" src="https://user-images.githubusercontent.com/87065622/172987699-f0d21340-bd4f-44f2-8d7b-36e4f31f9b36.png">
2x.png…]()
<img width="464" alt="CleanShot 2022-06-10 at 11 59 36@2x" src="https://user-images.githubusercontent.com/87065622/172987703-c000f543-599e-4e11-b346-c72ceb430dc4.png">

**Comment by imyelmo** [comment]
It is a bug. See issue [#29](https://github.com/blacs30/bitwarden-alfred-workflow/issues/129)

**Comment by victorchor2868** [comment]
> It is a bug. See issue [#29](https://github.com/blacs30/bitwarden-alfred-workflow/issues/129)

Ok. Understood, thanks for reply

**Comment by blacs30** [comment]
It seems to me to be 2 different issues.
#129 is about the unlock function.

@imyelmo  do you have issues logging in (e.g. the first time you want to use the workflow) or in connection with unlock?

**Comment by plummm** [comment]
I reproduce the same bug. It's my first time login, keep asking for password, I try both passward and api approaches. But it even ask for password when I was use API to login

**Comment by blacs30** [comment]
Is this still an issue? Have you found a way to get it working @victorchor2868 ?

**Comment by victorchor2868** [comment]
The issue is solved on the latest version. Thank you very much
