### ISSUE TITLE
"No Secrets Found" after unlocking

### ISSUE THREAD

**Issue by patrickfatrick** [blacs30/bitwarden-alfred-workflow#134]
Whenever I lock/unlock I have to manually re-sync secrets for any of them to show up. Is this by design?

**Comment by blacs30** [comment]
It's _by design_ currently. I'm aware of it and it needs a change for sure #133 should address it.

**Comment by blacs30** [comment]
This is changed now and secrets should appear after unlocking. The unlock process might take slightly longer though @patrickfatrick

**Comment by patrickfatrick** [comment]
You've made my day, sir. Thanks so much!
