### ISSUE TITLE
Search within words

### ISSUE THREAD

**Issue by tophee** [blacs30/bitwarden-alfred-workflow#135]
I wonder whether there is a way of getting the workflow to search not just words but also within words? For example, I was looking for my evernote password and typed `.bw evern` but nothing showed up. Turns out that the bitwarden item had `www.evernote.com` as its name. Once I searcher for `www.ever` I was able to find it so I changed the name to evernote. But it would be great if `www.wvernote.com` would be found when searching just for `evern`

**Comment by blacs30** [comment]
@tophee you can try using the fuzzy search instead of the Alfred search:

https://github.com/blacs30/bitwarden-alfred-workflow#search---filtermode

**Comment by tophee** [comment]
Excellent, this works! Thanks a lot!

Just wondering: what was the reason to change the default from fuzzy to Alfred?
