### ISSUE TITLE
Background sync is causing search window to pop up

### ISSUE THREAD

**Issue by luckman212** [blacs30/bitwarden-alfred-workflow#138]
Hey @blacs30 I tried to look at the go code (all instances where `searchAlfred()` function is called...) but couldn't pinpoint why this is happening. Sorry, I wanted to try to fix this myself.

Since installing 2.4.5, every time I run `./bitwarden-alfred-workflow -sync [-force]` it runs the sync **and then pops up Alfred's search box at the end.** I can see this maybe being useful if the cache needs to be rebuilt while actively using the workflow, and then you want to trigger the user's last query automatically when it's done... 

But It's problematic when using the background sync option, since this causes Alfred to pop up (usually with an empty box...) multiple times throughout the day. Maybe we need a new flag e.g. `-noquery` then we can add this to the `bw_cache_update.sh` script?

See [related bugreport I filed over on the Alfred Forum][1] (turns out this isn't an Alfred bug after all!)

And here's a video of it happening in realtime...

https://user-images.githubusercontent.com/1992842/194140420-dc66a9e6-127e-4973-8356-8888507cd3f0.mp4

[1]: https://www.alfredforum.com/topic/19037-503-b2084-alfred-popping-up-on-his-own/

**Comment by blacs30** [comment]
Will take a look soon. Didn't run the sync daemon in a while. There were a couple of changes regarding the sync functionality.

**Comment by blacs30** [comment]
It's caused by this line https://github.com/blacs30/bitwarden-alfred-workflow/commit/f825a5ff7fd6c456dc73a82d3fac04ae60263e23#diff-e53e29a949387095e371e28c11d6d340e50bf384ac957c1dc6a93b856312be76R109

**Comment by blacs30** [comment]
This is a simple fix that works for me. https://github.com/blacs30/bitwarden-alfred-workflow/pull/139/files

**Comment by luckman212** [comment]
Looks like a nice quick fix. I'll test as soon as 2.4.6 is available to download!

**Comment by luckman212** [comment]
@blacs30 Just tried this and happy to say it's working fine for me! Much obliged.
