### ISSUE TITLE
TOTP not working

### ISSUE THREAD

**Issue by waynehoover** [blacs30/bitwarden-alfred-workflow#140]
When trying to access a totp code nothing gets copied to the clipboard. 

Alfred 5.0.3
```
❯ bw --version
2022.10.0
```

log:
```
09:35:27 bitwarden.go:239: Getting item for id 42566764-6f5d-4dfc-bdfe-a99e00aaaaaa
09:35:27 bitwarden.go:242: Error making source key is:
MACs don't match of protectedkey and session key
09:35:27 bitwarden.go:278: crypto/aes: invalid key size 0
09:35:27 crypt_util.go:181: totp code: 555555
09:35:28 bitwarden.go:328: object is not map
09:35:28 workflow.go:405: ------------------ 824.513292ms ------------------
[09:35:28.535] Bitwarden v2[Run Script] Processing complete
[09:35:28.536] Bitwarden v2[Run Script] Passing output '' to Copy to Clipboard
[09:35:28.536] Bitwarden v2[Run Script] Passing output '' to Arg and Vars
[09:35:28.537] Bitwarden v2[Arg and Vars] Processing complete
[09:35:28.537] Bitwarden v2[Arg and Vars] Passing output 'Copy TOTP for user:
email@gmail.com' to Post Notification
```

has the totp output changed in recent `bw` versions that would make https://github.com/blacs30/bitwarden-alfred-workflow/blob/master/src/bitwarden.go#L326 fail?

**Comment by blacs30** [comment]
I just upgraded to the same Bitwarden CLI version but for me TOTP still works.

Did it work before? Does it work to get passwords via the workflow?

**Comment by waynehoover** [comment]
It did work before, I am able to get the passwords via the workflow, everything but totp codes seems to work. I wonder if it has anything to do with this `09:35:28 bitwarden.go:328: object is not map`

**Comment by blacs30** [comment]
Is it for all totp or only for one specific one?

**Comment by waynehoover** [comment]
All totp.

**Comment by blacs30** [comment]
The issue seems to start already before: `09:35:27 bitwarden.go:242: Error making source key is:`

Are you already a long term user of Bitwarden?
You might wanna try this rotation of the encryption key, so far that has helped those kind of issues:
https://bitwarden.com/help/account-encryption-key/#how-to-rotate-your-encryption-key

It will log you out of every device though.

**Comment by blacs30** [comment]
Yes that's the error. I just wonder why it would work to get passwords.

Do you use the Bitwarden cli often? Each time a new session is started there invalidates the Alfred wf session and the workflow needs to unlock again.

Could you try that in the workflow:
- unlock 
- get totp

**Comment by waynehoover** [comment]
@blacs30 That fixed it! Thanks so much.

**Comment by blacs30** [comment]
Awesome. Probably there were some left overs of the old Schema in the data.json file which the workflow couldn't handle probably.
