### ISSUE TITLE
Can't set `bwsetemail` 

### ISSUE THREAD

**Issue by rasulkireev** [blacs30/bitwarden-alfred-workflow#15]
Installed bitwarden-cli via HomeBrew. 
Downloaded and imported .alfred file from this repo.

Trying to set email but can't upon writing `bwsetemail <email>` can't press 'Enter' or confirm in any way. Doesn't happen for other functions. 

Thanks in advance!

**Comment by blacs30** [comment]
Thanks for opening this issue. 
Currently Alfred's UI doesn't change it's view after pressing "Enter", this should be fixed. However in the background it should be setting the email correctly. You can double check this in "Keychain Access" and search for "alfred-bitwarden".
If Alfred is allowed to show notifications then you should also see this kind of notification appearing
<img width="373" alt="Screenshot 2020-03-30 at 12 57 33" src="https://user-images.githubusercontent.com/11589882/77905320-55452380-7286-11ea-9d82-8749a280b5f6.png">
?

**Comment by rasulkireev** [comment]
@blacs30 Thank you. You are totally correct. Thanks for the quick response!
