### ISSUE TITLE
After login: cache expired

### ISSUE THREAD

**Issue by elchead** [blacs30/bitwarden-alfred-workflow#154]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/29373967/228431271-5248f531-9d58-46b3-afef-94e6171e69c2.png">
 I logged in using the apikey and afterwards I always get this window.

**Comment by blacs30** [comment]
Did you run a manual sync `.bwconfig sync` when this appears? Is this showing up anyways after the sync?
