### ISSUE TITLE
Unlocking issues after upgrading to Bitwarden-CLI v2023.8.2

### ISSUE THREAD

**Issue by glowacky** [blacs30/bitwarden-alfred-workflow#166]
After upgrading to Bitwarden-CLI v2023.8.2 via brew, I lost access to my login items via the workflow, and I've since had trouble unlocking my vault (even after deleting keychain items, re-installing workflow and CLI, testing with API key, etc.)

When I enter my master password to "unlock" the workflow, I see a message confirming that the vault was unlocked, but it doesn't seem to have worked:

![image](https://github.com/blacs30/bitwarden-alfred-workflow/assets/131688827/16a90f79-1ad6-41e6-8846-4de8f93da37a)

**Comment by blacs30** [comment]
I think I haven't updated myself to that version. Will check that later.

Are you using the europe region? 
Have you logged out fully and then logged in again via the workflow and also to test, via the cli?

**Comment by blacs30** [comment]
I can confirm, version `2023.8.2` is broken with the workflow. @glowacky

**Comment by blacs30** [comment]
@glowacky version 3.0.0 is out which also contains a fix for the 2023.8.2 version.

https://github.com/blacs30/bitwarden-alfred-workflow/releases/tag/3.0.0
