### ISSUE TITLE
Tells me I'm logged out when it's simply locked

### ISSUE THREAD

**Issue by bencgreen** [blacs30/bitwarden-alfred-workflow#17]
Every now and then when I search for an item or try to do a sync, I get an 'ERROR: not logged in' notification.  I login in using password and second factor - nothing happens.

Until I realised - when performing a search - that the vault was locked.  All I needed to do was a bwunlock.

Perhaps the ERROR not logged in message could be a little more helpful, if the vault is simply locked?

**Comment by blacs30** [comment]
Thank you for creating the issue and sorry for the inconvenience. 
The workflow needs some updates regarding login and lock checks. 
--check parameters has been added to the cli for login and unlock with version 1.7.1.

**Comment by blacs30** [comment]
This was fixed with release [2.0.0](https://github.com/blacs30/bitwarden-alfred-workflow/releases/tag/2.0.0)
