### ISSUE TITLE
Can't install autosync - PATH variable not set in workflow

### ISSUE THREAD

**Issue by jzadra** [blacs30/bitwarden-alfred-workflow#178]
Going to "Bitwarden Workflow Autosync Configuration" and then choosing Install gives the error "PATH variable not set in workflow".

![image](https://github.com/blacs30/bitwarden-alfred-workflow/assets/25590353/dad7bae7-08f0-4587-a53e-ac6f9dd2a215)

I've looked at the environment variables for the workflow and the only one that was blank was `BW_DATA_PATH`.  I set to the `~/Library/Application Support/Bitwarden CLI/` and still get the same error.  Further adding the file data.json to the path does not change the result either.

If it's literally referring to the PATH variable as opposed to that being a placeholder for one of the paths, that user config in the configuration builder is set to: `/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/bin:/usr/sbin:/opt/homebrew/bin`.  My bw is in the `/opt/homebrew/bin`

**Comment by luckman212** [comment]
I submitted a PR to fix this #176
already, but @blacs30 is away for a bit so it hasn't been released yet. If you clone the repo and overwrite the contents of your existing workflow dir with the latest versions it should fix it... or wait for 3.0.3
