### ISSUE TITLE
Can't login using bwlogin using workflow v1.3.0 and Alfred 4.0.9

### ISSUE THREAD

**Issue by SxC97** [blacs30/bitwarden-alfred-workflow#18]
I get the following error:

`env: node: No such file or directory`

<img width="429" alt="Screen Shot 2020-05-18 at 11 17 39 PM" src="https://user-images.githubusercontent.com/53032923/82284182-077f9a00-995e-11ea-8af2-faff6d2e9a3b.png">
 I have already set the username and confirmed it with keychain-access and set the server to https://bitwarden.com.

**Comment by blacs30** [comment]
@SxC97 thanks for creating the issue.
It looks like bitwarden cannot find node.
Did you install bitwarden via brew? Is the bitwarden-cli working in the terminal fine?

**Comment by SxC97** [comment]
I installed the bitwarden-cli using brew (it shows up using `brew list | grep bitwarden-cli`). Using any bitwarden command (even `bw --help`) in the terminal also gives the same error: `env: node: No such file or directory`.

**Comment by blacs30** [comment]
Bitwarden cli needs `node` to be installed on the mac and available in the PATH.  Basically run `brew install node` then test if node is available with e.g. `node --version`. If it returns `command not found` then please add the node installation path is added to the PATH environment variable.

**Comment by SxC97** [comment]
I reinstalled node and now I'm getting a *really* weird error.

When I try and login with `Set BitWarden Email Address` and `BitWarden Login` I get the error `You are already logged in as ********@*****.com`.
<img width="440" alt="Screen Shot 2020-05-26 at 1 19 18 AM copy" src="https://user-images.githubusercontent.com/53032923/82867058-b9cfd800-9eef-11ea-9bfd-bdbb0a48912e.png">


But when I try to use a function like `Sync BitWarden Vault` I get the error `Not currently logged into BitWarden`
<img width="440" alt="Screen Shot 2020-05-26 at 1 18 53 AM" src="https://user-images.githubusercontent.com/53032923/82866698-0b2b9780-9eef-11ea-9942-9b5b3a46cd7c.png">

This seems to be happening with the Bitwarden CLI as well.

**Comment by blacs30** [comment]
Can you try a `bwunlock` and then do a sync or just a normal `bw google` to search for a password?

**Comment by SxC97** [comment]
That fixed it. Thank you!
