### ISSUE TITLE
bwlogin silently fails

### ISSUE THREAD

**Issue by sdaitzman** [blacs30/bitwarden-alfred-workflow#19]
<img width="698" alt="Screen Shot 2020-05-19 at 6 16 48 PM" src="https://user-images.githubusercontent.com/1499476/82384035-f6d23100-99fc-11ea-9888-53790f545601.png">
<img width="377" alt="Screen Shot 2020-05-19 at 6 18 03 PM" src="https://user-images.githubusercontent.com/1499476/82384100-179a8680-99fd-11ea-954a-dae50832a690.png">

I have 2FA enabled, and have so far tried using lots of 2FA modes. Let me know if it's helpful to provide any other information to help debug this ☺️

**Comment by blacs30** [comment]
Thanks for reporting this issue.
When you login with the bitwarden cli in the terminal how many 2fa options does it show you?  -> how many 2fa options have you configured in the bitwarden web ui?
If only 1 then the mode has to be set to 0. 
Does that help?

**Comment by sdaitzman** [comment]
When I login using the CLI, it offers me two options.

On the web interface, I have 4 options configured.

What does the `bwset2famethod` option mean? Is is how many options you have?

**Comment by blacs30** [comment]
When I login via CLI it offers me 2 option.  To use email I set `bwset2famethod` to 1, for authenticator app I set 0.
I actually haven't tested the email 2fa method with the alfred workflow. Something for the new version.
<img width="226" alt="Screenshot 2020-05-20 at 14 30 32" src="https://user-images.githubusercontent.com/11589882/82446648-4f5e0880-9aa7-11ea-9988-3e6d9c7589b0.png">

**Comment by sdaitzman** [comment]
Thanks! I set the method to 0 to use the auth app, and it gave me a notification confirming. When I tried to run `bwlogin`, it prompted me for a password and a 2FA code, I entered both, and then it gave me no notification. When I try running `bwsync` afterwards, I get this notification saying I'm not logged in:

<img width="382" alt="Screen Shot 2020-05-20 at 8 38 37 AM" src="https://user-images.githubusercontent.com/1499476/82446913-7f8cb380-9a75-11ea-93a2-1fec72e686f1.png">

Am I missing a step?

**Comment by blacs30** [comment]
Mh, can you try `bw google` (or a different password name) - for me it showed me that the local wallet is locked. After a `bwunlock` I was able to do `bwsync` and also to run `bw google` to get my google passwords.

**Comment by sdaitzman** [comment]
Okay I have no idea what changed, but it works now?! I still see no notification after I run `bwlogin`, and I haven't changed anything except unlocking my CLI vault, but now I can sync and access values successfully.

I'll reopen this if I'm able to reproduce the same issue again.

**Comment by sdaitzman** [comment]
Thank you for all your help! <3

**Comment by blacs30** [comment]
Thanks for your patience. This workflow needs definitely some improvements. Glad it worked in the end.
