### ISSUE TITLE
Not copying anything to clipboard

### ISSUE THREAD

**Issue by trobinson65** [blacs30/bitwarden-alfred-workflow#20]
Running Alfred 4, allows login and pulls information from Bitwarden and returns results in Alfred window. Hitting enter after searching should copy password to clipboard but does nothing, no status message displayed from Alfred, nothing copied to clipboard.

Hitting shift and attempting to copy username to clipboard displays Alfred notification that the username has been copied, does not show up in clipboard.

**Comment by junaed** [comment]
Same here, updated alfred recently, current version 4.1[1167]

Found this on the log:
[10:22:55.824] Bitwarden CLI[Script Filter] Processing complete
[10:22:55.825] Bitwarden CLI[Script Filter] Passing output '(
    "url ommitted",
    "uuid ommitted"
)' to Run Script
[10:22:55.886] ERROR: Bitwarden CLI[Run Script] Traceback (most recent call last):
  File "/Users/user/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/51A38220-B41D-4047-B2E4-7FDE4919C87E", line 29, in <module>
    if 'error-noinstall' in details[0]:
IndexError: list index out of range

**Comment by junaed** [comment]
Hi @blacs30 it was working till yesterday for me. Updated alfred before wrapping up last night.
My bw-cli path is: 
$ which bw                                                                                                                         5.3s  Thu Jul 16 10:46:54 2020
/usr/local/bin/bw

From terminal, I can do below:
$ bw get item f002c51d-17ae-4eec

And got the json response back which shows my username and password.

Also updatred the cli:
$ brew upgrade bitwarden-cli                                                                                                  702ms  Thu Jul 16 10:51:03 2020
Warning: bitwarden-cli 1.11.0 already installed

**Comment by blacs30** [comment]
This is fixed with version [1.4.0](https://github.com/blacs30/bitwarden-alfred-workflow/releases/tag/1.4.0)
Thanks again for open this issue. It was due to a change in Alfred. 
I haven't found the exact place in the changelog but most likely something how they pass multiline text.
