### ISSUE TITLE
Error: You are already logged in as <email>

### ISSUE THREAD

**Issue by mmahmad** [blacs30/bitwarden-alfred-workflow#31]
Facing this error on Alfred v4.1[1167], latest v2 release of the workflow (as of Aug. 12).

1) Logged into my account (and entered 2fa). Login was successful.
2) Typing `.bw` (to search vault) automatically fills it to `.bwauth login`, as if I'm not logged in.
3) Re-logging in fails with error that I'm already logged in.

Logging out doesn't fix it, since I'm able to log in, but unable to search anything and am instead prompted to log in again (step 2).

I've been able to successfully log in and use it on another Mac, so not sure how to replicate this error.

**Comment by blacs30** [comment]
Thank you for opening this issue.

Are you running the latest version (2.0.3 as of writing) of the workflow?

Could you please paste the logs of the workflow? You can open the debug view in Alfred (select then the workflow and click the bug icon on the top right)

**Comment by mmahmad** [comment]
Sorry, I've been busy and haven't had the opportunity to confirm. I'll update over the weekend hopefully.

**Comment by mmahmad** [comment]
Yes, it was the latest update. However, I did a clean install of alfred+bitwarden-cli+bitwarden-alfred-workflow, and it seems to work now. 

Marking this as resolved.
