### ISSUE TITLE
Filtering with >1 search term has no effect

### ISSUE THREAD

**Issue by luckman212** [blacs30/bitwarden-alfred-workflow#40]
**VERSIONS**

- workflow v2.0.5
- Alfred 4.1.1 Build 1172
- `bw` CLI 1.11.0 cli installed from npm

**EXAMPLE**

I have the following 3 items in my vault:

- Microsoft Alpha
- Microsoft Bravo
- Microsoft Charlie
- Bravo Pizza

Searching using `'bw mic brav'` will return **ALL 3 Microsoft- items**. This is not ideal. Conversely, searching for `'brav micro'` returns both _Microsoft Bravo_ **AND** _Bravo Pizza_. Also not what we want. The 2nd search term is simply ignored.

I looked at the debug output as well as the source code, and it looks like awgo accepts the args correctly, but only the first arg is passed to the `bw` cli for searching.

I realize now that this seems to be a limitation of the bw cli itself, so I opened up [issue #163](https://github.com/bitwarden/cli/issues/163) over at [bitwarden/cli](https://github.com/bitwarden/cli). Until (or if?) that's sorted, I wonder if it would be better to simply dump ALL results from bw cli into the cache and then use [Alfred's Word Matching](https://www.alfredapp.com/help/workflows/inputs/script-filter/#resources) algorithm to handle the matching. That is more robust and allows for multiple search terms as well as arbitrary ordering of the keywords.

![image](https://user-images.githubusercontent.com/1992842/92634004-a0d21380-f2a1-11ea-8f6c-06884217e950.png)

Any thoughts?

**Comment by blacs30** [comment]
Thanks for creating this bug and explaining your observations.
I believe it’s a bug in the go code, because I actually dump all items into a cache (removed all secrets and secret containing items first). 
No bw search is used any longer, that was too slow.
I will check the code and should be able to fix it.

—-
Also another thought I had is to add the option to append the username to the item name. 
This way it’s easier to search for a specific user of a service:

E.g i habe 4 items all with the name google.com (because it’s the default) but each of these items is for a different user. Currently I cannot use the search except for google.com and then need to navigate or use the shortcuts.

With the username appended to the item I would have ‘google.com - abc’, ‘google.com - xyz’ etc 
This would be optional via configuration.

Does it make sense?

**Comment by luckman212** [comment]
> Also another thought I had is to add the option to append the username to the item name. ...
> This would be optional via configuration.
> Does it make sense?

Yes that sounds like possibly a good option to have. As an experiment I made the following 2 changes to the workflow settings:

![image](https://user-images.githubusercontent.com/1992842/92646479-8190b180-f2b4-11ea-98c0-6b01c4382ddd.png)

![image](https://user-images.githubusercontent.com/1992842/92646745-e2b88500-f2b4-11ea-8324-8404934efbdf.png)

![image](https://user-images.githubusercontent.com/1992842/92646647-bd2b7b80-f2b4-11ea-9bb4-991f7145f4e8.png)

It seems to work as expected, using Alfred's filtering now so I can shuffle around the search terms. I haven't found any problem with this yet. But I've only been using it for 5 minutes...

**Comment by blacs30** [comment]
Thank you for testing this config. 
I think that doesn't work fully with the setting `Alfred filters results` as the folder search is broken then and maybe other things.

However what I figured out, and didn't know before, is how the fuzzy search already works:

Here's a gif that shows it:
![fuzzy gif](https://raw.githubusercontent.com/deanishe/alfred-fuzzy/master/demo.gif)

Applying it to your example from the beginning you can filter this way:

`.bw mibr` and you will only get the result **Microsoft Bravo** 


Can you confirm that this is working for you too?

**Comment by luckman212** [comment]
Hmm, you're right, folder search is broken! I don't use that feature so I didn't even notice. 

1. I think folder search could be fixed by setting up a different workflow entry point/keyword specifically for folder search.

2. As for the fuzzy search, it's working for me using the "Alfred Filters Results" mode - but you have to enable Word Matching for match mode
![image](https://user-images.githubusercontent.com/1992842/92661240-2ec1f480-f2ca-11ea-9344-226d58005ace.png)

3. `.bw mibr` does not work for me, no. But that could be due to my config from point # 2

**Comment by claas-fridtjof-lisowski** [comment]
Regarding 3, that is working fine for me but not together with the change made in no 2.

I tried some searches with the config as in 2 but the search results are better IMO with the fuzzy search implementation in go - it's a little bit different than usually and I would update the documentation to explain that better - especially that no spaces are used.

No 1 would be an option in case it's really needed

**Comment by blacs30** [comment]
Regarding 3, that is working fine for me but not together with the change made in no 2.

I tried some searches with the config as in 2 but the search results are better IMO with the fuzzy search implementation in go - it's a little bit different than usually and I would update the documentation to explain that better - especially that no spaces are used.

No 1 would be an option in case it's really needed

**Comment by luckman212** [comment]
Ok, hmm well yes when disabling Alfred's Word matching, `.bw mibr` does work. But _NOT_ `.bw brmi` So that's still not as flexible or friendly since you have to remember in which order the words appear to be able to find things. 

I vote for a separate code path (can share the same keyword even) that has Alfred's filtering disabled just specifically for the folder searches. Seems that would be the best of both worlds.

**Comment by blacs30** [comment]
In the new release I migrated to the Alfred search as recommended by you. Thanks a lot!

**Comment by entekadesign** [comment]
This workflow is getting more and more useful! I prefer, however, the fuzzy search from previous versions. I found it more convenient to capture multi-word search targets by typing a few letters from each word in the target. Is there an easy way to make the search method customizable? Thanks again for your work!

**Comment by blacs30** [comment]
@entekadesign I see, the search mode is an opinion thing. I've [released a new version](https://github.com/blacs30/bitwarden-alfred-workflow/releases/tag/2.1.1) with a gif to demonstrate how it's possible to change between the "old" and the "new" search mode.

[https://github.com/blacs30/bitwarden-alfred-workflow#search---filtermode](https://github.com/blacs30/bitwarden-alfred-workflow#search---filtermode)
