### ISSUE TITLE
Feature Request: Customize Default (Unmodified) Command

### ISSUE THREAD

**Issue by entekadesign** [blacs30/bitwarden-alfred-workflow#42]
The ability to customize modified keys in the re-written workflow is wonderful; but I have been unable to customize the command executed without a modifier key. I had made some modifications to the previous version that allowed me to open the URL from a selected Bitwarden item without using a modifier key (thus changing the default behavior and making the experience more similar to Alfred's 1password integration). I don't see an easy way to make a similar modification to this version, so I wonder whether anyone else would find it convenient to open URLs without having to use a modifier key.

And thanks, Claas, for a faster, even more feature-packed version of software that was already very useful in previous versions!

**Comment by blacs30** [comment]
Thanks for the feature request. That makes totally sense to me to also customize the default behavior without a modifier key being used.

Good to hear you like the workflow.
Do you use this workflow to open urls and then use the Bitwarden browser extension to auto fill user and password?

Though the workflow is already faster than the old one it’s still too slow to get the secrets (at least I’m not fully satisfied yet)

**Comment by entekadesign** [comment]
Claas,

Yes, I use the workflow exactly as you describe. The “secrets” retrieval of the current version of your workflow is a bit slower than the 1password integration with Alfred, but it is already quite fast, and more than adequate for my purposes.

Thank you again for your work, and for your quick response!

Best,
  
MARCO TOMASCHETT
marco@entekadesign.com <mailto:marco@entekadesign.com>
www.entekadesign.com <http://www.entekadesign.com/>
646•335•5990 <tel:+16463355990>

**Comment by blacs30** [comment]
@entekadesign I've released a new version which includes a feature to customize all modifier keys and their actions including the default (non modifier) action.
