### ISSUE TITLE
Feature Request: manual sync command/option

### ISSUE THREAD

**Issue by JasperV** [blacs30/bitwarden-alfred-workflow#46]
Hello @blacs30,

Do you think it would be possible to add an additional option/command to manually trigger the syncing of the secrets?
I often find myself adding new passwords in bitwarden which I then need shortly after and throughout the day. I know I can lower the cache time for the syncing, but this results in too much syncing on days that I do not add any passwords.

Cheers

**Comment by blacs30** [comment]
Hi @JasperV 
that command exists already. I guess the README needs to highlight available options of `.bwconf`

<img width="574" alt="Screenshot 2020-10-06 at 09 40 59" src="https://user-images.githubusercontent.com/11589882/95172852-32a54180-07b8-11eb-96dd-bd8735e5296f.png">
