### ISSUE TITLE
Cache that persists across reboots

### ISSUE THREAD

**Issue by jkaan** [blacs30/bitwarden-alfred-workflow#47]
Hi there!

Perhaps I'm mistaking and it is actually persisted to disk. What I would like is if it's possible to persist the items on disk so that I wouldn't have to sync every time. My passwords don't change that much so that would be perfect for me.

I can imagine there are other users that would find this useful as well :), most likely you'll use 20% of the passwords 80% of the time and those are fine if they aren't as up-to-date since they wouldn't change that much.

I would be open to creating a PR for this too if you could point me in the right direction.

**Comment by blacs30** [comment]
Hi @jkaan,
it is already possible to configure the cache timeout. I've just done a reboot and also checked against the bitwarden cli documentation. The session key which is saved in keychain does not expire by itself.

If you want to reboot or go sleep and come back to an unlocked bitwarden workflow please increase these 2 workflow config variables:

`CACHE_AGE` and `SYNC_CACHE_AGE` [https://github.com/blacs30/bitwarden-alfred-workflow/blob/master/README.md](https://github.com/blacs30/bitwarden-alfred-workflow/blob/master/README.md)

**Comment by blacs30** [comment]
PS: the cache is persisted to disk, to the alfred workflow data directory. It doesn't contain any secret fields and is additionally encrypted.
