### ISSUE TITLE
Automatic timed cache refresh in background

### ISSUE THREAD

**Issue by luckman212** [blacs30/bitwarden-alfred-workflow#49]
_Not an issue, just wanted to open a discussion..._

I got a little frustrated when calling up this workflow and waiting for it to sync when I needed a password right away. I know I am being impatient, but I thought it would be a better experience if there was a way to have this refresh automatically in the background.

I created a solution, which anyone can try: [**bw-cache-update**](https://github.com/luckman212/bw-cache-update)

It's pretty simple to install (follow the README) but I think it would be better if this was made "native" by doing the following:

- bundle the LaunchAgent (plist) and Bash script directly within the workflow itself
- make a workflow trigger that self-installs (symlink) the LaunchAgent
- add some workflow variables to control frequency of the background sync (or maybe just piggyback off `SYNC_CACHE_AGE`?)

I am open to helping with this / submitting a PR but I wanted to get opinions first on whether this was a good idea or if anyone sees any problems with the implementation. Also if you encounter any problems please open an [issue](https://github.com/luckman212/bw-cache-update/issues).

Big thank you as always to @blacs30 for this amazing workflow! 👍

**Comment by luckman212** [comment]
@blacs30 one question I have for you: my script omits the following 2 commands:
```
bitwarden-alfred-workflow -cache
bitwarden-alfred-workflow -icons
```
I believe just triggering `bitwarden-alfred-workflow -sync -force` should be "enough" but I am not sure I understand well enough the other 2 functions. They are commented out in the script but could easily be enabled.

**Comment by Sandmania** [comment]
Giving some more control over the sync process in general seems like a good idea to me. I could see use for the following at least:

1. The current functionality: autosync after timeout when accessing the vault
2. The proposed functionality in this issue: autosync after timeout in the background
3. And I'd like to propose a third one: only sync on command

I'm sure there are more, too, but these I think would be most useful. Thoughts?

**Comment by luckman212** [comment]
> I'd like to propose a third one: only sync on command

I wonder if this is already possible by setting `SYNC_CACHE_AGE` to **0**? Other than that I think that should cover all the cases. Will look for some comment from @blacs30

**Comment by blacs30** [comment]
> `SYNC_CACHE_AGE` to 0

Actually that's a good idea, currently it would cause an endless loop of syncs. 


> 1. The current functionality: autosync after timeout when accessing the vault
> 2. The proposed functionality in this issue: autosync after timeout in the background
> 3. And I'd like to propose a third one: only sync on command

re 1. correct, and I like the idea to set this to 0 to disable it
re 2. I'm not sure if it's possible to install a `LaunchAgent` plist configuration to run a background sync. If someone knows this already it would be helpful to comment here. 
Another option would be to sync in the background and let the user to query secrets from the cache but block the action get retrieve a secret (it's doing a `bw sync` and a `bw get items` and then iterating over all items, clearing out all secret keys and creating an encrypted cache (json file on disk) from it) 
re 3. There is already a manual sync possibility `.bwconfig sync`

Going to answer the other questions regarding the cli options later.

**Comment by luckman212** [comment]
> re 2. I'm not sure if it's possible to install a `LaunchAgent` plist configuration to run a background sync

@blacs30 that is actually what my top post is about, if you check it again (TLDR; yes it is possible!) - see https://github.com/luckman212/bw-cache-update] in case you missed it 👍

**Comment by blacs30** [comment]
@luckman212 I saw that and I like the approach and idea. What I had in mind was to use the workflow to install the plist or run the shell file.
So the option to install a background sync could be part of the workflow, however I'm not sure how much the workflows are sandboxed.

**Comment by luckman212** [comment]
I'm testing out right now to see if the workflow can create the plist & bash script, install & load it into launchd.  Will post back shortly.

**Comment by blacs30** [comment]
with [release 2.2.0](https://github.com/blacs30/bitwarden-alfred-workflow/releases/tag/2.2.0) , among other things, I've added the behaviour that `SYNC_CACHE_AGE ` = 0 disables auto sync

**Comment by luckman212** [comment]
@blacs30 awesome! 👍  

I guess I am a few hours late with this, but here's a 2.1.2-test version that has a built in self-installing auto-updater (installs LaunchAgent).  I tested it on my 2 Macs and it works. I'd love for anyone else to test though.

I added 2 env vars: `AUTO_HOUR` and `AUTO_MIN` so the user can choose what time of day the auto-update happens. This workflow contains an updated version of the `bw_cache_update.sh` script as well, so everything is self-contained, no need for any external downloads or plists (the script generates the .plist dynamically).

I think the only caveat is that when it first runs, the user might get a macOS security prompt that "bash wants to control Alfred etc" which you have to click OK (once) on. Please let me know how you get on...

[Bitwarden-v212-test.alfredworkflow.zip](https://github.com/blacs30/bitwarden-alfred-workflow/files/5462354/Bitwarden-v212-test.alfredworkflow.zip)

**Comment by luckman212** [comment]
I just made an updated version based on your 2.2.0

If you can, please test

[Bitwarden_v221-test.alfredworkflow.zip](https://github.com/blacs30/bitwarden-alfred-workflow/files/5462407/Bitwarden_v221-test.alfredworkflow.zip)

**Comment by luckman212** [comment]
One case that isn't currently possible is if someone wants the auto sync to happen more than once a day.

I have an idea for reducing `AUTO_HOUR` and `AUTO_MIN` into a single `AUTO_SYNC_TIMES` field that allows multiple comma-separated times to be entered eg `8:15,13:45,23:00`. Bash can split those out later.

**Comment by blacs30** [comment]
Nice script. Will test it over the weekend.
<StartupInterval> in the plist could also be used but maybe multiple times per day is more user friendly than using seconds.
... and it reminded me that I don't like these launchagents and -daemons in macOS.

**Comment by Sandmania** [comment]
> One case that isn't currently possible is if someone wants the auto sync to happen more than once a day.
> 
> I have an idea for reducing `AUTO_HOUR` and `AUTO_MIN` into a single `AUTO_SYNC_TIMES` field that allows multiple comma-separated times to be entered eg `8:15,13:45,23:00`. Bash can split those out later.

How about a cron-like syntax?

**Comment by luckman212** [comment]
@Sandmania Interesting idea, but launchd on macOS doesn't directly support crontab syntax. I did find a [crontab spec parser for Go](https://godoc.org/github.com/robfig/cron) but that's probably overkill here. There are basically 2 native options for timed execution:

1. `StartCalendarInterval` (one or more specific times of day, on specified days/weekdays/days of month)
2. `StartInterval` (non-specific interval timer that triggers every N seconds)

You can also combine methods 1 and 2 if necessary. I think for most people, just a simple `StartCalendarInterval` that fires once per day will be sufficient. But I am working on a new version of the script that allows for both scenarios above.

**Comment by luckman212** [comment]
Here's a new version 2.2.1-**test2** with these changes:

- supports dynamically generated sync schedule 🎉 &nbsp; using new workflow env variable `AUTOSYNC_TIMES` (you can enter a single time, or multiple comma-separated times, eg `8:15,23:45`

- added a `--link` arg/function which will create a convenience symlink to the **bw_cache_update.sh** script in your `/usr/local/bin` so you can execute it any time from Terminal outside of the workflow (for testing, calling from other scripts etc)

- trigger keyword is now `.bwauto` and you must pass either `--install` or `--link` as arg

- better error handling, a bit more console output and the LaunchAgent will log stderr and stdout to `/tmp/com.lisowski-development.alfred.bitwarden_autosync.{err,out}`

- cleaned up the functions a bit

Please test - once #53 gets resolved I think we're close to hopefully closing this out

**download**
[Bitwarden v2.2.1-test2.alfredworkflow.zip](https://github.com/blacs30/bitwarden-alfred-workflow/files/5467984/Bitwarden.v2.2.1-test2.alfredworkflow.zip)

**Comment by luckman212** [comment]
New version 2.2.1-**test3**

changes:

- added list filter to `.bwauto` trigger to make it easier to choose actions
- added option for 'every **N** seconds' style of sync interval in addition to specific times of day (auto parsed, just type a number instead of time of day in the `AUTOSYNC_TIMES` env var)
- improved error handling, logging and notifications
- added env var `AUTOSYNC_SCRIPT_DIR` to define target of script symlink (defaults to `/usr/local/bin`)
- some icons (if ugly please change!)

Please let me know how this is working! I guess the next challenge is rewriting the whole thing in golang... 😛 

[Bitwarden v2.alfredworkflow-221-test3.zip](https://github.com/blacs30/bitwarden-alfred-workflow/files/5483064/Bitwarden.v2.alfredworkflow-221-test3.zip)

**Comment by blacs30** [comment]
I like this approach with an external scheduler application. When I was searching through the Alfred forum I wasn't able to find anything that Alfred can do this, more importantly it is not made as a scheduler application. Therefore I am fine with the solution via shell script as a LaunchAgent.

Another possibility, but not really an option here, would be via a workflow background job [https://github.com/deanishe/awgo/blob/master/background.go#L42-L61](https://github.com/deanishe/awgo/blob/master/background.go#L42-L61). But that wouldn't work because latest at a system restart the job will stop from running in the background.

Thanks for all your work already.
I was able to install the first version without issues. I'm not having that many secrets but will try the test3 with the "every N seconds" option and create some new secrets in between.

**Comment by luckman212** [comment]
@blacs30 Great I am glad you're ok with the solution. Until we figure out what's causing #53, the temporary fix as I discovered is to replace the `bitwarden-alfred-workflow` binary with your debug one...

**Comment by luckman212** [comment]
**2.2.1-test4** - with debug `bitwarden-alfred-workflow` for now, since it works.

[Bitwarden v2.2.1-test4.zip](https://github.com/blacs30/bitwarden-alfred-workflow/files/5484942/Bitwarden.v2.2.1-test4.zip)

**Comment by blacs30** [comment]
Looks very nice. 
Could you add the parameter `-L` for the find command in line 148 in the bash script?
I have the workflow symlinked and that option follows symlinks using find - otherwise the script tells me that the workflow hasn't been found.

**Comment by luckman212** [comment]
That seems like a good idea. I just want to do a bit more testing but I'll send an update shortly.

**Comment by luckman212** [comment]
Here's v 2.2.1-**test5**-fixdecrypt

changes:

- added `-L` flag to support case when the workflow itself is symlinked
- env var setting moved to a function to enable debug testing using `-v` parameter (source script and then you can run `./bitwarden-alfred-workflow` commands interactively...
- honor `DEBUG` flag set in workflow 

[Bitwarden-2.2.1-test5-fixdecrypt.alfredworkflow.zip](https://github.com/blacs30/bitwarden-alfred-workflow/files/5532468/Bitwarden-2.2.1-test5-fixdecrypt.alfredworkflow.zip)

**Comment by luckman212** [comment]
Hey @blacs30 
No pressure or anything as I am sure you're busy. Just pinging to see if you need anything else done here, or if you'd like me to submit an actual PR for merging?

**Comment by blacs30** [comment]
hi @luckman212
that would be really helpful if you have time for a PR that add those changes.
Thanks a lot.

**Comment by luckman212** [comment]
Sure, I'll do it. Are your latest changes committed already? I want to base the PR on the most recent version (only asking because [on 11/11 you sent me a debug version](https://github.com/blacs30/bitwarden-alfred-workflow/issues/53#issuecomment-725779511) of `bitwarden-alfred-workflow` which fixed a decryption issue). But the latest public commit to the repo says 10/29.

**Comment by blacs30** [comment]
@luckman212 the master branch contains now all changes regarding the decryption fix and other issues. I'm waiting then for your PR before I release the next version.

**Comment by mmahmad** [comment]
Is there a workaround until this is merged?

 I often have to wait for a minutes or so while the vault syncs immediately after my laptop wakes up from sleep. Is there a way to pause sync until I resume it explicitly?

**Comment by blacs30** [comment]
@mmahmad you can set `CACHE_AGE` and `SYNC_CACHE_AGE` to a high value (e.g `43200` for 30 days)

**Comment by stevelacey** [comment]
Nice to see this is already supported, but `CACHE_AGE` / `SYNC_CACHE_AGE` being `0` aka off by default is super odd, makes the workflow seem buggy to anyone that creates new accounts on the regular.

The workflow has failed for me more than it has worked, and I only just now bothered researching why, because clearly it wasn't autosyncing, I'm sure there are others that have just uninstalled rather than debug the issue.

Sync by default has got to be enabled, majority of users will want it, if there's issues with it, inform them when they set up the workflow, or at least let them configure it via `bconfig` so it's obvious to enable/change, currently you have find this thread.

Anyway nice work, I'll sandwich my comment with compliments, aside from this issue the workflow works great and I tried a bunch of similar things in the past like `lastpass-cli` and they all sucked, so great job, glad to finally put my mouse away 👏🏼

**Comment by blacs30** [comment]
@stevelacey thanks for your input and feedback. I fully agree, just ran into that issue myself and didn't like it at all.
In the next release I will enable the auto sync again as default.

**Comment by stevelacey** [comment]
Switching my vars to `0` didn't help much, the problem all stems from the cache being unqueryable during syncing, really the sync needs to happen behind the seems and just serve cache while it's happening.

**Comment by blacs30** [comment]
With [version 2.3.0](https://github.com/blacs30/bitwarden-alfred-workflow/releases/tag/2.3.0) the background sync has been added. See also [the README](https://github.com/blacs30/bitwarden-alfred-workflow#enable-auto-background-sync) this should help.
