### ISSUE TITLE
Potential Improvement

### ISSUE THREAD

**Issue by zoenglinghou** [blacs30/bitwarden-alfred-workflow#5]
When the vault is locked, it would be nice if the user could unlock it by hitting `return`, instead of entering `bwunlock` again.

**Comment by claaslisowski** [comment]
Return would be even more nice, agree. Currently just hold the function key (`fn`) and press `return` to unlock.

**Comment by blacs30** [comment]
Return would be even more nice, agree. Currently just hold the function key (`fn`) and press `return` to unlock.

**Comment by blacs30** [comment]
This should be covered by #8

**Comment by blacs30** [comment]
This was fixed with release [2.0.0](https://github.com/blacs30/bitwarden-alfred-workflow/releases/tag/2.0.0)
