### ISSUE TITLE
type any keyword but return same： syncing bitwarden secrets

### ISSUE THREAD

**Issue by blackholll** [blacs30/bitwarden-alfred-workflow#54]
![image](https://user-images.githubusercontent.com/6269605/99209343-ebba5b00-27fd-11eb-9c0b-3b90a7aae396.png)
![image](https://user-images.githubusercontent.com/6269605/99209429-1efcea00-27fe-11eb-9de8-f11993488797.png)

alred 4.2.1 

![image](https://user-images.githubusercontent.com/6269605/99209592-726f3800-27fe-11eb-8f61-3607da9e1834.png)

**Comment by blacs30** [comment]
Thanks for opening this issue. I noticed that myself - the reason for that is that when typing `.bw` it starts checking if the secrets have been synced otherwise it will start with it. Since `.bw` is a subset of `.bwauth` and `.bwconfig` the sync process starts. 
With #49 we get a background sync, if additionally a sync check on start of the workflow is needed I could set a flag `ENABLE_STARTUP_SYNC` true/false.
A workaround for right now you can type `123.bwauth` and then remove the `123` again - then the sync check will not be triggered.

**Comment by blackholll** [comment]
I didn't understand the workaround。  now I can't search any password.  I  type any keyword about bitwarden but return sync all the same。  is the ‘123’ in '123.bwauth'  is password's name?  I should type it in alfred or in the command line?    when I type this the alfred will Identified as a website。

![image](https://user-images.githubusercontent.com/6269605/99662217-eb40ef00-2a9f-11eb-9cff-5fe2f216400c.png)


![image](https://user-images.githubusercontent.com/6269605/99663785-1b898d00-2aa2-11eb-8acd-753b8e244b14.png)

![image](https://user-images.githubusercontent.com/6269605/99663884-45db4a80-2aa2-11eb-90e9-89a45864bd1b.png)

**Comment by blacs30** [comment]
The workaround I mentioned is only to get to the config or auth settings not to search secrets.
The sync has to finish once completely, for me it takes typically around 1 minute max. 
If it's the first time that the workflow is used the Bitwarden user has to login, if that is required the workflow will jump itself to the `login` setting.
Additionally if any of the [cache workflow variables](https://github.com/blacs30/bitwarden-alfred-workflow#advanced-features--configuration) is set to 0 the workflow is put into a sync endless loop.

**Comment by luckman212** [comment]
> the workflow is put into a sync endless loop.

Yikes- sounds bad @blacs30. Could this be avoided by counting loops in a workflow variable or a sentinel file and bailing out after X loops?

**Comment by blacs30** [comment]
What I've tested now was to disable the automatic sync functionality (both for secrets and the cache) per default (set to 0).
If sync is enabled the lowest possible value is 30 (that is minutes) (if variable is set to e.g. 2 the actual value which is used is 30 )
