### ISSUE TITLE
Differences between -sync / -cache / -icons?

### ISSUE THREAD

**Issue by luckman212** [blacs30/bitwarden-alfred-workflow#55]
Hi @blacs30 

Related to https://github.com/blacs30/bitwarden-alfred-workflow/issues/49#issuecomment-714187794, I was hoping you could give a little info about the differences between these 3 parameters for `bitwarden-alfred-workflow`:

    -sync
    -cache
    -icons

I want to make sure the background refresh is optimized and not wasting time or bandwidth with unnecessary calls. Right now it passes `-sync -force` parameters which I think is right for this situation (not sure about `-force` tbh).

But I wonder what `-cache` does? I assume icons are refreshed when running `-sync` (but maybe not) Do we need to call that separately in order to keep the icons updated?

![image](https://user-images.githubusercontent.com/1992842/99991803-80373700-2d83-11eb-94a2-190c1828bea5.png)

**Comment by blacs30** [comment]
I think the usage output should have some more.

The differences are:

- sync: (sync the secrets via bw sync and get the latest from the server), runs -cache as last step
- cache: updates the cached data (that is all items except the secrets) it is updated by running `bw list items` (this also works without internet connection I think) and removes all the secrets from it. The cached data is stored encrypted but I didn't want to have any secrets in it. On start of the workflow it is decrypted and read and the existing items in the workflow are presented from it.
- icons: this iterates over all `login` items which contain a url and downloads the favicon for it. we don't want to run that too often as rate limit could set in. Using `https://icons.duckduckgo.com/ip3` for it.

Icons are also refreshed when presenting items in the workflow, that is where the variable `AUTO_FETCH_ICON_CACHE_AGE` configures how often the workflow should do that as it doesn't make sense to repeat it every time and fail every time again.

**Comment by luckman212** [comment]
ok so for the background sync do you suggest that `-sync` is enough then? The icon cache will be updated as needed by the workflow itself during normal use, and since -sync runs -cache, no need to double up on that? (btw that is how it currently is set to run, I just commented out the other 2 commands so they don't actually run...)

![image](https://user-images.githubusercontent.com/1992842/99998485-c0e77e00-2d8c-11eb-80a9-281a251f9170.png)

**Comment by blacs30** [comment]
Yes that sufficient to get the secrets and the cache updated.
