### ISSUE TITLE
not usable when using alfred sync between 2 macs

### ISSUE THREAD

**Issue by jappyjan** [blacs30/bitwarden-alfred-workflow#56]
I'm syncing my workflows using the Alfred Sync Folder technique which results in me .bw not working on one mac but on the other.

Path and Exec are the same on booth macs.

It actually fails silently:
shows no error,
shows no result at all

<img width="822" alt="Bildschirmfoto 2020-11-25 um 11 11 19" src="https://user-images.githubusercontent.com/10154260/100213478-f4521600-2f0e-11eb-98a4-3010b15b7879.png">

**Comment by blacs30** [comment]
@jappyjan 
you are right, this can unfortunately happen. I use Nextcloud and have the same issue: https://github.com/nextcloud/server/issues/6725

Dropbox might be able to keep the permissions. 

In a new version I will going to set execution permissions for the workflow binary.
You can do it yourself right now.
Open the workflow folder in the terminal (via right click on the workflow), then give executable permissions to the binary:

`chmod +x bitwarden-alfred-workflow`
