### ISSUE TITLE
Typo: `Securitey` → `Security`

### ISSUE THREAD

**Issue by luckman212** [blacs30/bitwarden-alfred-workflow#57]
Small typo here :)

https://github.com/blacs30/bitwarden-alfred-workflow/blob/07e4383c7814be8cb525909e693b6762a71ddd00/config.go#L425

![image](https://user-images.githubusercontent.com/1992842/101090363-8ba91000-3584-11eb-95e1-c0693e227e4d.png)

**Comment by blacs30** [comment]
Thanks for finding this. 
Will hopefully find some time over the weekend to take care of most of the open issues, including this one.
