### ISSUE TITLE
Copied password is error message in release 2.2.0

### ISSUE THREAD

**Issue by daniel-stoneuk** [blacs30/bitwarden-alfred-workflow#63]
Hi! Love the Alfred workflow. Just updated to release 2.2.0 and found my passwords aren't copied correctly. 

`runtime error: slice bounds out of range [:32] with capacity 0` is copied to my clipboard instead.

Thanks.

**Comment by luckman212** [comment]
@daniel-stoneuk I had this problem too. Could you please try the unreleased [2.2.1-test5-fixdecrypt](https://github.com/blacs30/bitwarden-alfred-workflow/files/5532468/Bitwarden-2.2.1-test5-fixdecrypt.alfredworkflow.zip) version & report back? I'm working on a PR that should be pushed up later today with those changes rolled in, along with the other recent fixes from @blacs30 that should help.

**Comment by daniel-stoneuk** [comment]
Whoops so sorry, I didn't think to check #53. I've just tested the unreleased version and it's working fine for me. The decryption does seem to be slightly faster compared to what it was before which is excellent.

I'll close this issue now and pay more attention when creating new ones in in the future 😅  . Cheers.
