### ISSUE TITLE
Malformed session key: cannot login

### ISSUE THREAD

**Issue by Yoshi2889** [blacs30/bitwarden-alfred-workflow#7]
When logging in via `bwlogin` to the bitwarden hosted instance with an account with 2fa enabled (not sure if relevant), the session key is malformed and only contains `[object` as can be seen in Keychain:

![image](https://user-images.githubusercontent.com/1280380/55283060-d86d2a00-5351-11e9-8b90-752bb979722e.png)

I'm not sure how to go about debugging this.

**Comment by blacs30** [comment]
Thanks for creating this issue. 
Did you set the the bw 2fa option to on?
Was the login successful?
Are you using the app authentication like Authy? 

Does bitwarden work fine via cli in the terminal? 
Basically I’m not doing anything else then using that bw binary to get the session key. It’s happening in this script https://github.com/blacs30/bitwarden-alfred-workflow/blob/master/workflow-main-scripts/bw-login.py

I think it’s possible to set a different mfa method. I don’t know however if that makes a difference. 
You could run the commands from that python script and check if the output looks fine.

I don’t know if yubikey work.

Hope that helps little bit for the beginning.

Can you let me know the bw cli Version?

**Comment by Yoshi2889** [comment]
I'm using Authy as my TOTP app. I don't know if the login was successful; the workflow did mention that it was. I have set bw2fa to on.

I tried using the bitwarden CLI (version 1.7.2 installed via Homebrew) and couldn't login, it returned [object Object] and exited with a non zero exit code.

It might be because I tried many login attempts at once, I'll try again in a couple hours. Doesn't look like it's related to the workflow though...

**Comment by glowacky** [comment]
I'm also unable to login with 2FA. I set bw2fa to "On" and at first I got the following notification after entering the code: "env: no such file or directory". After fixing some symlinks in Node, the message changed to "2FA config not correct/missing"

**Comment by Yoshi2889** [comment]
Doesn't seem to be related to the issue I'm having, though. I had the "2FA config not correct/missing" message but after setting the server URL again it went away.

I just tried again and it's still borked. I'll file a bug with the bitwarden cli client in the meantime.

**Comment by claaslisowski** [comment]
I also use CLI version 1.7.2. 
The command which is executed is basically this `/usr/local/bin/bw --raw login email@address.com password --code 123456`
@glowacky can you test if that is working via the Terminal application. Expected output is a session key.

Keychain should show (at least) these entries for bitwarden:
![Screenshot 2019-04-01 at 11 26 42](https://user-images.githubusercontent.com/33903475/55317582-16ad3b00-5471-11e9-89fa-09c29830a8be.png)

**Comment by blacs30** [comment]
I also use CLI version 1.7.2. 
The command which is executed is basically this `/usr/local/bin/bw --raw login email@address.com password --code 123456`
@glowacky can you test if that is working via the Terminal application. Expected output is a session key.

Keychain should show (at least) these entries for bitwarden:
![Screenshot 2019-04-01 at 11 26 42](https://user-images.githubusercontent.com/11589882/55317898-ba96e680-5471-11e9-8ec5-b10db7322c7f.png)

**Comment by Yoshi2889** [comment]
I tried that command locally and it doesn't work, returns [object Object] still. I do have all the entries that you show in my keychain, even when login "fails".

https://github.com/bitwarden/cli/issues/64 This is the issue I've opened.

**Comment by Yoshi2889** [comment]
Not sure why, but resetting the server variable in bw-cli's config seems to have helped: `bw config server bitwarden.com`

It's working great now, thanks for trying to help!

**Comment by glowacky** [comment]
@blacs30 the workflow started working correctly once I logged in using bw-cli. Thanks!
