### ISSUE TITLE
Feature Request: Use clip board to paste both email and password onto clip board

### ISSUE THREAD

**Issue by kylemh** [blacs30/bitwarden-alfred-workflow#73]
This way, I can act like this:

- Go to URL that needs login info
- CMD + ENTER for Alfred
- ".bw URL HERE"
- Enter
- Go back to browser
- Focus on email field, PASTE
- Focus on pw field, PASTE

**Comment by blacs30** [comment]
This could be achieved by using Alfreds internal clipboard, if that’s what you mean.
However the password shouldn’t be added to it. Therefore I could see the order
- paste password first
- Then open Alfreds Clipboard and pick the username

- However sometimes the username must be entered first so it’s not a solution which works always
- 

Another way I’ve seen it that you just open the url via the workflow and then have the browser bitwarden plugin to auto insert configured. Maybe that’s a feasible workaround for you
