### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by damiencuvillier** [blacs30/bitwarden-alfred-workflow#74]
For 2 or 3 days, i'm unable to login to my account. (connected to a specific server)

I'm using Alfred 4

It seems not store typed password. 
No error message, nothing happens, either when I type a good or bad password or MFA code. 

i.e. If I try to change server URL, it does not store it in `info.plist` file => i have to set it directly in info.plist file manually.

**Comment by damiencuvillier** [comment]
Here is Log output 

``` dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.67.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found```

**Comment by damiencuvillier** [comment]
Finally, issue is linked with libicui18n.67.dylib library file
It looks for 67 version, and I've only got 68 (certainly after a brew upgrade). 

I did not know how to fix this issue


I've just tried ```
 brew upgrade bitwarden-cli
```
 
And it's worked.

**Comment by jpcercal** [comment]
I had the same issue and `brew upgrade bitwarden-cli` saved me, thanks for sharing it @damiencuvillier. =)
