### ISSUE TITLE
Password generation

### ISSUE THREAD

**Issue by pascalinger** [blacs30/bitwarden-alfred-workflow#75]
Hi there,

First off: A big thank you for the workflow. I can only imagine how much work this must have been.

I do have two ideas which you could consider if they are of any use to you as well:

- **Premium necessary**: A shortcut to retrieve the mfa token that is generated within the app for premium users would be handy.
- The ability to generate a password (either via saved settings or last used settings from within the account/app) and copy it to clipboard would be incredibly handy.

Thank you anyhow for your hard work on this. I enjoy using it and it already saved me tons of time.

Best,
Pascal

**Comment by pascalinger** [comment]
Forget the TOTP request, just found it. :-)

**Comment by blacs30** [comment]
For passwords I'd recommend this workflow https://github.com/deanishe/alfred-pwgen
since the bitwarden workflow doesn't edit secrets I also don't see the purpose to have a built-in password generator when there is such a good one available from daeanishe.
