### ISSUE TITLE
Search improvement

### ISSUE THREAD

**Issue by pascalinger** [blacs30/bitwarden-alfred-workflow#77]
When searching in the Bitwarden Browser extension or the Web Vault, they use wildcard searches so i can look for any word within the title, url or username of the specific vault item.

Unfortunately, the search within this workflow is very specific and doesnt find an item if i look for app.com, but the actual url and title of the item are account.app.com.

Maybe we could change that.

**Comment by blacs30** [comment]
You are correct, the search is different. 
I see a limitation in the way how Alfred is doing the search, it's searching through the main title content (I might be wrong though). Maybe there is also a better way to do the search than I have implemented. 
What I can do for now is to add the option to append the urls to the end of the username. This way it's at least possible to search via domain.

Additionally, in case you haven't, check also the fuzzy search vs the alfred internal search: https://github.com/blacs30/bitwarden-alfred-workflow#search---filtermode

**Comment by blacs30** [comment]
As said I've added the URLs to the title so that it's possible to search by item name, username and url.  The last 2 options can be disabled with these 2 workflow variables TITLE_WITH_USER and TITLE_WITH_URLS.
