### ISSUE TITLE
Cache won’t update

### ISSUE THREAD

**Issue by babramczyk** [blacs30/bitwarden-alfred-workflow#78]
Recently, any changes I made to Bitwarden entries aren’t reflected.

I’ve tried both uninstalling and reinstalling this workflow and the `bw` CLI, but to no avail.

It seems like it never tries to update my secrets anymore either, FWIW.

**Comment by blacs30** [comment]
In a newer the configs SYNC_CACHE_AGE and CACHE_AGE are set to 0, that disables the auto sync. 

This will be changed in the next release because it causes confusion as a default fresh install doesn't sync.

As a workaround you can try do sync manually via `.bwconf` and then type `sync`
