### ISSUE TITLE
Error the Bitwarden command wasn't found.

### ISSUE THREAD

**Issue by andrewbihl** [blacs30/bitwarden-alfred-workflow#84]
<img width="578" alt="Screen Shot 2021-06-18 at 5 37 50 PM" src="https://user-images.githubusercontent.com/16709744/122626213-f2dc6c80-d05d-11eb-8f07-5307c5ab9ad9.png">

I ran into this issue. I tried to fix by appending `:$(which bw)` to PATH, replacing PATH entirely, and changing the BW_EXEC var. None worked.

Any recommendations for how to debug?

**Comment by andrewbihl** [comment]
I also tried restarting Alfred.

**Comment by blacs30** [comment]
Have you tried to change the `BW_EXEC` Alfred workflow variable to the path where the bitwarden cli is installed?

**Comment by andrewbihl** [comment]
Yes, I did did try that. It didn't seem to work.

Nonetheless, the initial issue has gone away. It still doesn't work, but the issue is now different so I will close this issue and create a new one.
