### ISSUE TITLE
Default set2famethod does not work for app auth

### ISSUE THREAD

**Issue by mmahmad** [blacs30/bitwarden-alfred-workflow#9]
The README states that `set2famethod` is optional to set. However, the default value does not allow logging into Bitwarden if 2fa (with auth app) is set.

I had to set `set2famethod` to "0" which worked for me.

**Comment by blacs30** [comment]
Thanks for reporting it! Open for PRs. Otherwise I'll put this on the list for #8

**Comment by blacs30** [comment]
I recently came accross the same issue and will need to update documentation and preferably the code:

When there is more than 1 2FA configured, like auth app and email, then the CLI asks interactively which one to choose. In that case it is required to set the 2famethod to 0 or 1 etc..

**Comment by blacs30** [comment]
This was fixed with release [2.0.0](https://github.com/blacs30/bitwarden-alfred-workflow/releases/tag/2.0.0)
