### ISSUE TITLE
[Feature Request] Generate password

### ISSUE THREAD

**Issue by mmahmad** [blacs30/bitwarden-alfred-workflow#90]
Hi,

I'd love to be able to generate a password through this workflow, perhaps with `.bw genpwd` with options to select the complexity of the password.

**Comment by claas-fridtjof-lisowski** [comment]
Duplicate of #75 

For passwords I'd recommend this workflow https://github.com/deanishe/alfred-pwgen

**Comment by blacs30** [comment]
Duplicate of #75 

For passwords I'd recommend this workflow https://github.com/deanishe/alfred-pwgen
