### ISSUE TITLE
Question: can I use bw cli from the command line while still using this workflow?

### ISSUE THREAD

**Issue by kelbyers** [blacs30/bitwarden-alfred-workflow#91]
When I unlock bw from a command terminal, it seems to lock the vault for the workflow, and when I unlock in the workflow, it locks the command line.

Is there any way to use both without interfering with each other?

**Comment by blacs30** [comment]
You can use this script to achieve that https://github.com/luckman212/bitwarden-cli-helpers
Currently there is no other way yet.
