### ISSUE TITLE
Everytime I try to do something it logs me out of my account

### ISSUE THREAD

**Issue by aaSchcolnik** [blacs30/bitwarden-alfred-workflow#92]
I just downloaded and set up this workflow, i log in and everything's fine, after trying to do absolutely ANYTHING it always says im logged out, i dont have any knowledge when it comes to programming this is just a cry for help.

https://user-images.githubusercontent.com/86570811/129606191-887e1bdf-2813-4a95-a42c-00485ee86eae.mp4

**Comment by blacs30** [comment]
Can you check if you have entries in keychain which start with 'com.lisowski'. 
Have you checked these steps https://github.com/deanishe/awgo/wiki/Catalina? Just in case it's a permission thing and no warning appears.
Have you checked the debug logs of the Alfred workflow (click on this bug in the alfred ui and run the workflow)
I've also just updated the workflow to the newest external dependencies, not sure if that helps.
Are you on macOS big sur?

**Comment by aaSchcolnik** [comment]
Thank you very much for your reply, i will try everything you said here and i'll let you know if everything's working

**Comment by aaSchcolnik** [comment]
Hi, so I downloaded your updated version, erased any trace of the older version and now the flow seems to be working, I finally managed to copy a password, thank you for your time

**Comment by luckman212** [comment]
@aaSchcolnik glad you solved it. This latest version is working nicely for me too. 👍  I just pushed a very small PR #95
